name: Deepseek Auto Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm install

      - name: 打包项目
        run: npm run build

      # 可选：上传打包产物到 GitHub Actions
      - name: 上传打包产物
        uses: actions/upload-artifact@v4
        with:
          name: deepseek-build
          path: dist/
